name: minimal_mp3_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
        
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^14.0.2
  just_audio: ^0.9.37
  path_provider: ^2.1.3
  shadcn_ui: ^0.4.1
  supabase_flutter: ^2.0.0
  youtube_explode_dart: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
      - family: Geist
        fonts:
          - asset: fonts/Geist-Regular.ttf  
  assets:
    - .env